context:
  name: docling
  version: "2.25.2"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/docling-${{ version }}.tar.gz
  sha256: 5251b49661e7b39fe0b64e836ae44f18d0a303758ba0d8e3c4ef53f59a00d011

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - docling = docling.cli.main:app

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.0.0,<3.0.0
    - docling-core >=2.19.0,<3.0.0
    - docling-ibm-models >=3.4.0,<4.0.0
    - docling-parse >=3.3.0,<4.0.0
    - filetype >=1.2.0,<2.0.0
    - pypdfium2 >=4.30.0,<5.0.0
    - pydantic-settings >=2.3.0,<3.0.0
    - huggingface_hub >=0.23,<1
    - requests >=2.32.2,<3.0.0
    - easyocr >=1.7.0,<2.0.0
    - certifi >=2024.7.4
    - rtree >=1.3.0,<2.0.0
    - scipy >=1.6.0,<2.0.0
    - typer >=0.12.5,<0.13.0
    - python-docx >=1.1.2,<2.0.0
    - python-pptx >=1.0.2,<2.0.0
    - beautifulsoup4 >=4.12.3,<5.0.0
    - pandas >=2.1.4,<3.0.0
    - marko >=2.1.2,<3.0.0
    - openpyxl >=3.1.5,<4.0.0
    - lxml >=4.0.0,<6.0.0
    - pillow >=10.0.0,<12.0.0
    - tqdm >=4.65.0,<5.0.0
  run_constraints:
    - tesserocr >=2.7.1,<3.0.0
    - onnxruntime >=1.7.0,<2.0.0
    - transformers >=4.42.0,<5.0.0

tests:
  - python:
      imports:
        - docling
      # `pip check` fails because:
      # - "scikit-image 0.24.0 has requirement numpy>=1.23, but you have numpy 1.22.4."
      pip_check: false
      python_version: ${{ python_min }}.*
  - script:
      - docling --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Docling PDF conversion package
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/DS4SD/docling

extra:
  recipe-maintainers:
    - hadim
